name: geofence_service_in_app
description: This plugin is a fork of geofence_service with updated dependencies.
version: 0.0.1
homepage: https://github.com/volkanakbayir/geofence_service

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  fl_location: ^2.0.0+1
  flutter_foreground_task: ^4.1.0
  flutter_activity_recognition: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.pravera.geofence_service
        pluginClass: GeofenceServicePlugin
      ios:
        pluginClass: GeofenceServicePlugin
